POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  graphData(ids: "person-500", key:"6GzCesnexrzgnDv3FfxbHBrb"){
    nodes {
      id
      name
      poster
      popularity
      voteAverage
      voteCount
    }
    links {
      source
      target
      roles
    }
  }
} 