POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL
Access-Control-Allow-Origin: '*

query {
  search(term:"SE7EN", key:"6GzCesnexrzgnDv3FfxbHBrb") {
    id            
    name         
    poster
    entity
    type
    popularity
    voteAverage
    voteCount
    knownForDepartment
  }    
}