POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  saveGraph(ids:"person-500,person-287,person-192",counts:[7,12,20] key:"6GzCesnexrzgnDv3FfxbHBrb") {
    status
    msg
    resourceId
    resourceSlug
  }
}