POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  nodes(ids: ["person-500,person-287,person-192,movie-137113"], count: 5) {
    id
    name
    poster
  }
  links(ids: ["person-500,person-287,person-192,movie-137113"], count: 6) {
    source
    target
    roles
  }
}