POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  graphData(ids:["person-500","person-287","person-192"]) {
    id
    nodes {
      id
      name
      poster
      type
      entity
    }
    links { 
      source
      target
      roles
    }
  }
}