POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  details(id:"person-500") {
    id
    summary
    year
    imdbId
    name
    popularity
    poster
  }    
}