POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  nodes(ids: ["person-500"], count: 15) {
    id
    name
    poster
    type
  }
  links(ids: ["person-500"], count: 15) {
    source
    target
    roles
  }
}