# GET http://localhost:3000/test

POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  links{
    source
    target
    roles
  }
  nodes {
    id: _id
    name
    poster
  }
}