POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  link(movieIds: [628], personIds: [500]) {
    source
    target
    roles
  }
}

# nodes {
#   id
#   name
#   poster
# }
