POST http://localhost:3000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query {
  nodes(personIds: [500, 192], movieIds: [74], count: 5) {
    id
    name
    poster
  }
  links(personIds: [500, 192], movieIds: [74], count: 5) {
    source
    target
    roles
  }
}