search_result = {"page": 1,
	"results": 
	  [
      {"adult": false,
      "id": 500,
      "name": "Tom Cruise",
      "original_name": "Tom Cruise",
      "media_type": "person",
      "popularity": 35.196,
      "gender": 2,
      "known_for_department": "Acting",
      "profile_path": "/8qBylBsQf4llkGrWR3qAsOtOU8O.jpg",
      "known_for": 
        [{"adult": false,
          "backdrop_path": "/4V1yIoAKPMRQwGBaSses8Bp2nsi.jpg",
          "id": 137113,
          "title": "Edge of Tomorrow",
          "original_language": "en",
          "original_title": "Edge of Tomorrow",
          "overview": 
          "Major Bill Cage is an officer who has never seen a day of combat when he is unceremoniously demoted and dropped into combat. Cage is killed within minutes, managing to take an alpha alien down with him. He awakens back at the beginning of the same day and is forced to fight and die again... and again - as physical contact with the alien has thrown him into a time loop.",
          "poster_path": "/xjw5trHV7Mwo61P0kCTy8paEkgO.jpg",
          "media_type": "movie",
          "genre_ids": [28, 878],
          "popularity": 50.116,
          "release_date": "2014-05-27",
          "video": false,
          "vote_average": 7.596,
          "vote_count": 12291},
        {"adult": false,
          "backdrop_path": "/19AqfWi8S99tDmp7hskCeDQuwLU.jpg",
          "id": 75612,
          "title": "Oblivion",
          "original_language": "en",
          "original_title": "Oblivion",
          "overview": 
          "Jack Harper is one of the last few drone repairmen stationed on Earth. Part of a massive operation to extract vital resources after decades of war with a terrifying threat known as the Scavs, Jack’s mission is nearly complete. His existence is brought crashing down when he rescues a beautiful  stranger from a downed spacecraft. Her arrival triggers a chain of events that  forces him to question everything he knows and puts the fate of humanity in his hands.",
          "poster_path": "/eO3r38fwnhb58M1YgcjQBd3VNcp.jpg",
          "media_type": "movie",
          "genre_ids": [28, 878, 12, 9648],
          "popularity": 36.212,
          "release_date": "2013-04-10",
          "video": false,
          "vote_average": 6.608,
          "vote_count": 9690},
        {"adult": false,
          "backdrop_path": "/hqyjzDRCs1N5gEsh2gklzPdsEFD.jpg",
          "id": 56292,
          "title": "Mission: Impossible - Ghost Protocol",
          "original_language": "en",
          "original_title": "Mission: Impossible - Ghost Protocol",
          "overview": 
          "Ethan Hunt and his team are racing against time to track down a dangerous terrorist named Hendricks, who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.",
          "poster_path": "/psiWp3VTjznfokmGQG9uqiiknQQ.jpg",
          "media_type": "movie",
          "genre_ids": [28, 53, 12],
          "popularity": 52.961,
          "release_date": "2011-12-07",
          "video": false,
          "vote_average": 7.05,
          "vote_count": 8715}]},
      {"adult": false,
      "backdrop_path": "/uRokRYuqQZf5v1JJERKhKTmJXLn.jpg",
      "id": 984430,
      "title": "James Corden's Top Gun Training with Tom Cruise",
      "original_language": "en",
      "original_title": "James Corden's Top Gun Training with Tom Cruise",
      "overview": "When \"Top Gun: Maverick\" star Tom Cruise calls you up to hang out for the day, you say yes. And for James Corden, that meant having Tom pilot you in two different fighter planes, pushing the limits of gravity and James's stomach.",
      "poster_path": "/e2EILRtu7b6qu4TuwU7BpyHop68.jpg",
      "media_type": "movie",
      "genre_ids": [28, 35, 99],
      "popularity": 24.267,
      "release_date": "2022-06-01",
      "video": false,
      "vote_average": 6.143,
      "vote_count": 14},
      {"adult": false,
      "backdrop_path": "/kThxkMh2hNTUzFqPp72GfvXf5x0.jpg",
      "id": 765522,
      "title": "Tom Cruise: An Eternal Youth",
      "original_language": "en",
      "original_title": "Tom Cruise: An Eternal Youth",
      "overview": 
        "After 40 years, Tom Cruise continues to push the envelope in film. Exposing ones' heart to the world through their work is not only risky business, as far as Cruise is concerned, it is the only way to achieve an end that feels complete.",
      "poster_path": "/MQwWS1iBzUkpyjNFV8Je6dFoIU.jpg",
      "media_type": "movie",
      "genre_ids": [99],
      "popularity": 5.653,
      "release_date": "2020-10-05",
      "video": false,
      "vote_average": 6.694,
      "vote_count": 18},
      {"adult": false,
      "backdrop_path": nil,
      "id": 1010758,
      "title": "Untitled Tom Cruise and Christopher McQuarrie Musical",
      "original_language": "en",
      "original_title": "Untitled Tom Cruise and Christopher McQuarrie Musical",
      "overview": "An \"original song and dance-style musical\" by Christopher McQuarrie and Tom Cruise.",
      "poster_path": nil,
      "media_type": "movie",
      "genre_ids": [10402],
      "popularity": 0.915,
      "release_date": "",
      "video": false,
      "vote_average": 0.0,
      "vote_count": 0},
      {"adult": false,
      "backdrop_path": nil,
      "id": 1010759,
      "title": "Untitled Tom Cruise and Christopher McQuarrie Action Film",
      "original_language": "en",
      "original_title": "Untitled Tom Cruise and Christopher McQuarrie Action Film",
      "overview": "An \"original action film with franchise potential\" by Christopher McQuarrie and Tom Cruise.",
      "poster_path": nil,
      "media_type": "movie",
      "genre_ids": [28],
      "popularity": 0.6,
      "release_date": "",
      "video": false,
      "vote_average": 0.0,
      "vote_count": 0},
      {"adult": false,
		 "backdrop_path": "/mpJwppwUCtV5cGjb6wYF7p219S2.jpg",
		 "id": 53849,
		 "title": "Cruise Cat",
		 "original_language": "en",
		 "original_title": "Cruise Cat",
		 "overview": 
			"Tom is the official cat on the cruise ship S.S. Aloha, but he'll be kicked off if the captain finds even one mouse. That one, of course, is Jerry, who sneaks on board just before sailing.",
		 "poster_path": "/vQpmz4zCHxRYOQMQUgS373bSZvt.jpg",
		 "media_type": "movie",
		 "genre_ids": [16, 35],
		 "popularity": 3.132,
		 "release_date": "1952-10-18",
		 "video": false,
		 "vote_average": 6.6,
		 "vote_count": 31}
    ],
	"total_pages": 1,
	"total_results": 6
 }

TmdbService.build_from_results(search_result)

return

Person.create!({
  :adult=>false,                        
  :also_known_as=>
   ["Том Круз",
    "トム・クルーズ",
    "ทอม ครูซ",
    "湯姆·克魯斯",
    "톰 크루즈",
    "توم كروز",
    "Thomas Cruise Mapother IV",
    "Τομ Κρουζ",
    "טום קרוז",
    "Thomas 'Tom' Cruise",
    "汤姆·克鲁斯",
    "TC",
    "Toms Krūzs",
    "تام کروز"],
  :biography=>
   "Thomas Cruise Mapother IV (born July 3, 1962), known professionally as Tom Cruise, is an American actor and producer. One of the world's highest-paid actors, he has received various accolades, including an Honorary Palme d'Or and three Golden Globe Awards, in addition to nominations for three Academy Awards. His films have grossed over $4 billion in North America and over $11.1 billion worldwide, making him one of the highest-grossing box office stars of all time.\n\nCruise began acting in the early 1980s and made his breakthrough with leading roles in the comedy film Risky Business (1983) and action film Top Gun (1986). Critical acclaim came with his roles in the dramas The Color of Money (1986), Rain Man (1988), and Born on the Fourth of July (1989). For his portrayal of Ron Kovic in the latter, he won a Golden Globe Award and received a nomination for the Academy Award for Best Actor. As a leading Hollywood star in the 1990s, he starred in several commercially successful films, including the drama A Few Good Men (1992), the thriller The Firm (1993), the horror film Interview with the Vampire (1994), and the romance Jerry Maguire (1996). For the latter, he won a Golden Globe Award for Best Actor and received his second Academy Award nomination. Cruise's performance as a motivational speaker in the drama Magnolia (1999) earned him another Golden Globe Award and a nomination for the Academy Award for Best Supporting Actor.\n\nSince then, Cruise has largely starred in science fiction and action films, establishing himself as an action star, often performing his own risky stunts. He has played Ethan Hunt in all six of the Mission: Impossible films from 1996 to 2018. His other notable roles in the genre include Vanilla Sky (2001), Minority Report (2002), The Last Samurai (2003), Collateral (2004), War of the Worlds (
 2005), Knight and Day (2010), Jack Reacher (2012), Oblivion (2013), Edge of Tomorrow (2014), and Top Gun: Maverick (2022), with Maverick being his highest-grossing film
 .\n\nDescription above from the Wikipedia article Tom Cruise, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
  :birthday=>"1962-07-03",
  :deathday=>nil,
  :gender=>2,
  :homepage=>"http://www.tomcruise.com",
  :id=>500,
  :imdb_id=>"nm0000129",
  :known_for_department=>"Acting",
  :name=>"Tom Cruise",
  :place_of_birth=>"Syracuse, New York, USA",
  :popularity=>35.196,
  :profile_path=>"/8qBylBsQf4llkGrWR3qAsOtOU8O.jpg"
})

Movie.create!({
  :adult=>false,
  :backdrop_path=>"/nH6hPhJq3EEv9CnBZgXU3IQnpJo.jpg",
  :belongs_to_collection=>nil,
  :budget=>132000000,
  :genres=>[{:id=>12, :name=>"Adventure"}, {:id=>53, :name=>"Thriller"}, {:id=>878, :name=>"Science Fiction"}],
  :homepage=>"https://amblin.com/movie/war-of-the-worlds/",
  :id=>74,
  :imdb_id=>"tt0407304",
  :original_language=>"en",
  :original_title=>"War of the Worlds",
  :overview=>
   "Ray Ferrier is a divorced dockworker and less-than-perfect father. Soon after his ex-wife and her new husband drop off his teenage son and young daughter for a rare weekend visit, a strange and powerful lightning storm touches down.",
  :popularity=>40.017,
  :poster_path=>"/6Biy7R9LfumYshur3YKhpj56MpB.jpg",
  :production_companies=>
   [{:id=>4, :logo_path=>"/gz66EfNoYPqHTYI4q9UEN4CbHRc.png", :name=>"Paramount", :origin_country=>"US"},
    {:id=>7, :logo_path=>"/vru2SssLX3FPhnKZGtYw00pVIS9.png", :name=>"DreamWorks Pictures", :origin_country=>"US"},
    {:id=>44, :logo_path=>nil, :name=>"Cruise/Wagner Productions", :origin_country=>"US"},
    {:id=>56, :logo_path=>"/cEaxANEisCqeEoRvODv2dO1I0iI.png", :name=>"Amblin Entertainment", :origin_country=>"US"}],
  :production_countries=>[{:iso_3166_1=>"US", :name=>"United States of America"}],
  :release_date=>"2005-06-28",
  :revenue=>603873119,
  :runtime=>117,
  :spoken_languages=>[{:english_name=>"English", :iso_639_1=>"en", :name=>"English"}],
  :status=>"Released",
  :tagline=>"They're already here.",
  :title=>"War of the Worlds",
  :video=>false,
  :vote_average=>6.487,
  :vote_count=>7352
})